//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="Interface1")]
public interface Interface1
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface1/Insert", ReplyAction="http://tempuri.org/Interface1/InsertResponse")]
    void Insert(string name, double size, string path, string format, System.DateTime date);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface1/Insert", ReplyAction="http://tempuri.org/Interface1/InsertResponse")]
    System.Threading.Tasks.Task InsertAsync(string name, double size, string path, string format, System.DateTime date);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface1/Delete", ReplyAction="http://tempuri.org/Interface1/DeleteResponse")]
    void Delete(string par);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface1/Delete", ReplyAction="http://tempuri.org/Interface1/DeleteResponse")]
    System.Threading.Tasks.Task DeleteAsync(string par);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface1/newCol", ReplyAction="http://tempuri.org/Interface1/newColResponse")]
    void newCol(string par);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface1/newCol", ReplyAction="http://tempuri.org/Interface1/newColResponse")]
    System.Threading.Tasks.Task newColAsync(string par);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface1/deleteCol", ReplyAction="http://tempuri.org/Interface1/deleteColResponse")]
    void deleteCol(string par);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface1/deleteCol", ReplyAction="http://tempuri.org/Interface1/deleteColResponse")]
    System.Threading.Tasks.Task deleteColAsync(string par);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface1/Update", ReplyAction="http://tempuri.org/Interface1/UpdateResponse")]
    void Update(string path, string column, string value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface1/Update", ReplyAction="http://tempuri.org/Interface1/UpdateResponse")]
    System.Threading.Tasks.Task UpdateAsync(string path, string column, string value);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface Interface1Channel : Interface1, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class Interface1Client : System.ServiceModel.ClientBase<Interface1>, Interface1
{
    
    public Interface1Client()
    {
    }
    
    public Interface1Client(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public Interface1Client(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Interface1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Interface1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void Insert(string name, double size, string path, string format, System.DateTime date)
    {
        base.Channel.Insert(name, size, path, format, date);
    }
    
    public System.Threading.Tasks.Task InsertAsync(string name, double size, string path, string format, System.DateTime date)
    {
        return base.Channel.InsertAsync(name, size, path, format, date);
    }
    
    public void Delete(string par)
    {
        base.Channel.Delete(par);
    }
    
    public System.Threading.Tasks.Task DeleteAsync(string par)
    {
        return base.Channel.DeleteAsync(par);
    }
    
    public void newCol(string par)
    {
        base.Channel.newCol(par);
    }
    
    public System.Threading.Tasks.Task newColAsync(string par)
    {
        return base.Channel.newColAsync(par);
    }
    
    public void deleteCol(string par)
    {
        base.Channel.deleteCol(par);
    }
    
    public System.Threading.Tasks.Task deleteColAsync(string par)
    {
        return base.Channel.deleteColAsync(par);
    }
    
    public void Update(string path, string column, string value)
    {
        base.Channel.Update(path, column, value);
    }
    
    public System.Threading.Tasks.Task UpdateAsync(string path, string column, string value)
    {
        return base.Channel.UpdateAsync(path, column, value);
    }
}
